name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: rutujap1998
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: rutujap1998/frontend:latest

    - name: Build and push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: rutujap1998/backend:latest

    - name: Deploy to Frontend Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTEND_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull rutujap1998/frontend:latest
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend \
            -p 80:80 \
            -e REACT_APP_API_URL=${{ secrets.BACKEND_URL }} \
            rutujap1998/frontend:latest

    - name: Deploy to Backend Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull rutujap1998/backend:latest
          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend \
            -p 3000:3000 \
            -e NODE_ENV=production \
            -e PORT=3000 \
            rutujap1998/backend:latest